services:
  server:
    build: .
    ports:
      - "3141:3141"
    networks:
      - kwispel-server_gedeeldNetwerk
  frontend:
    build: ./kwispel-client
    ports:
      - "5173:5173"
    networks:
      - kwispel-server_gedeeldNetwerk
networks:
  kwispel-server_gedeeldNetwerk: