services:
  server:
    build: 
      context: .
      dockerfile: ./kwispel-server/Dockerfile
    ports:
      - "3141"
    networks:
      - kwispel-netwerk
  frontend:
    build: 
      context: ./kwispel-client
    ports:
      - "5173"
    networks:
      - kwispel-netwerk
  proxy:
    build:
      context: ./kwispel-proxy
    ports:
      - "5172:5172"
    depends_on:
      - server
      - frontend
    networks:
      - kwispel-netwerk
networks:
  kwispel-netwerk: