services:
  server:
    build: 
      context: .
      dockerfile: ./kwispel-server/Dockerfile
    ports:
      - "3141:3141"
    networks:
      - kwispel-server_gedeeldNetwerk
  frontend:
    build: 
      context: ./kwispel-client
    ports:
      - "5173:5173"
    networks:
      - kwispel-server_gedeeldNetwerk
networks:
  kwispel-server_gedeeldNetwerk: