services:
  frontend:
    build: ./kwispel-client
    ports:
      - "5173"
    networks:
      - netwerk
  server:
    build: .
    ports:
      - "3141"
    networks:
      - netwerk
networks:
  netwerk: